#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
if [ "$(uname -s)" == "Darwin" ]
then
  brew bundle --file ./brewfile/mac
else
  brew bundle --file ./brewfile/linux
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
